//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_catalogos
    {
        public int Idproducto { get; set; }
        public string DescripcionProducto { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public int Estado { get; set; }
    }
}
